"""Domain-neutral robustness-region and counterfactual contracts."""

from .connector import (
    ConnectorIdentity,
    DiscreteActionSpec,
    ExactActionInvariance,
    FormalDistanceLayer,
    MetricCertificate,
    ObservationSpec,
    PolicyConnector,
    SearchConnector,
)
from .policy import (
    ACTION_NORMALIZATION_SCHEMA_VERSION,
    ActionCacheRecord,
    ActionOracle,
    ActionShapeError,
    ActionValidationError,
    CacheRestoreError,
    ModelActionOracle,
    ModelCompatibilityError,
    OracleStats,
    TableActionOracle,
    TableThenModelActionOracle,
    UnknownTableKeyError,
    normalize_discrete_action,
)
from .models import (
    ContinuationMismatchError,
    CounterfactualExistence,
    CounterfactualProjection,
    CounterfactualSelection,
    InvalidSearchOptions,
    MetricCertificationError,
    MinimumBasis,
    SearchCompleteness,
    SearchContinuation,
    SearchExtent,
    SearchMetadata,
    SearchOptions,
    SearchResult,
    SearchStats,
    StateRecord,
    StopReason,
)
from .search import compute_rr

__all__ = [
    "ACTION_NORMALIZATION_SCHEMA_VERSION",
    "ActionCacheRecord",
    "ActionOracle",
    "ActionShapeError",
    "ActionValidationError",
    "CacheRestoreError",
    "ConnectorIdentity",
    "ContinuationMismatchError",
    "CounterfactualExistence",
    "CounterfactualProjection",
    "CounterfactualSelection",
    "DiscreteActionSpec",
    "ExactActionInvariance",
    "FormalDistanceLayer",
    "InvalidSearchOptions",
    "MetricCertificate",
    "MetricCertificationError",
    "MinimumBasis",
    "ModelActionOracle",
    "ModelCompatibilityError",
    "ObservationSpec",
    "OracleStats",
    "PolicyConnector",
    "SearchConnector",
    "SearchCompleteness",
    "SearchContinuation",
    "SearchExtent",
    "SearchMetadata",
    "SearchOptions",
    "SearchResult",
    "SearchStats",
    "StateRecord",
    "StopReason",
    "TableActionOracle",
    "TableThenModelActionOracle",
    "UnknownTableKeyError",
    "normalize_discrete_action",
    "compute_rr",
]
