# env_name: "MiniGrid-Fetch-5x5-N2-v0"
model_type: "PPO"
# total_timesteps: 100000
n_steps: 128
batch_size: 64
ent_coef: 0.01
learning_rate: 0.0003
gamma: 0.99
gae_lambda: 0.95
# max_grad_norm: 0.5
# ortho_init: True
# net_arch: "small"
# activation_fn: "relu"
n_epochs: 10
# clip_range: 0.2
normalize_advantage: True
device: "cpu"