#sample env: "MiniGrid-Fetch-5x5-N2-v0", "MiniGrid-Empty-8x8-v0"
# env_name: "MiniGrid-Fetch-5x5-N2-v0"
# env_name: "MiniGrid-Empty-Random-5x5-v0"

# env_name: "MiniGrid-Empty-8x8-v0"
env_name: "MiniGrid-Empty-Random-6x6-v0"

total_timesteps: 100000

# Possible values for representation: "symbolic", "image", "standard"
# representation: "standard"
# representation: "image"
representation: "symbolic"

# Define render mode for gymnasium.make
render_mode: "rgb"

#parameters for symbolic representation
max_objects: 10
max_walls: 32

# Reward wrappers configuration
reward_wrappers:
  action_bonus: false  # Enable/disable ActionBonus wrapper
  position_bonus: false  # Enable/disable PositionBonus wrapper

# By default evaluation is done on original reward and the value is False
evaluate_with_modified_reward: False